// components/CookieDisclaimer.vue
<template>
  <div class="cookie-disclaimer" v-if="!hasRead">
    <small class="text-xs">
      {{ $t('data-security.cookie-disclaimer') }}
    </small>

    <div class="flex justify-end px-8 pt-2 text-xs">
      <button class="mr-8 font-bold primary">
        {{ $t('data-security.read-more') }}
      </button>
      <button class="button primary" @click="markAsRead()">
        {{ $t('data-security.ok') }}
      </button>
    </div>
  </div>
</template>

<script>
export default {
  props: {
    i18nScope: { type: String },
  },
  data: () => ({
    hasRead: true,
  }),
  mounted() {
    this.hasRead = window.localStorage.getItem('midwife-cookie-read');
  },
  methods: {
    markAsRead() {
      window.localStorage.setItem('midwife-cookie-read', true);
      this.hasRead = true;
    },
  },
};
</script>

<style lang="postcss">
.cookie-disclaimer {
  @apply fixed p-3 text-justify text-white shadow-lg;
  position: fixed;
  bottom: 0;
  background-color: var(--mw-secondary);
  z-index: 50;
  left: 20%;
  right: 20%;

  @media (max-width: 767px) {
    left: 0;
    right: 0;
  }
}
</style>

// src/general/components/cookie-disclaimer.component.tsx
import { Button, ButtonType } from "@/general/components/button.component";
import { useState } from "react";
import { useTranslation } from "react-i18next";

export function CookieDisclaimer() {
  const { t } = useTranslation();
  const [wasRead, setWasRead] = useState(
    sessionStorage.getItem("cookies-accepted") === "true",
  );

  function markAsRead() {
    setWasRead(true);
    sessionStorage.setItem("cookies-accepted", "true");
  }

  return (
    <div>
      {!wasRead && (
        <div className="fixed z-20">
          <div className="fixed p-3 text-justify text-white shadow-xl left-0 right-0 md:left-[20%] md:right-[20%] z-50 bg-primary bottom-4">
            <small className="text-xs">
              {t("data-security.cookie-disclaimer")}
            </small>

            <div className="flex justify-end gap-4 px-8 pt-2 text-xs">
              <Button
                className="text-white button primary hover:text-primary"
                link={`/data-security`}
                type={ButtonType.BORDER_GRAY}
              >
                {t("data-security.read-more")}
              </Button>

              <Button onClick={markAsRead} type={ButtonType.SECONDARY}>
                {t("data-security.ok")}
              </Button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
